### ISSUE TITLE
arm64 compatibility

### ISSUE THREAD

**Issue by sunjam** [homelabapi/homelabapi#1]
Hi, wondering about arm64 compatibility for running this on a Pi-like device.  Thanks either way for considering!

**Comment by gregdotca** [comment]
This will definitely be coming, hopefully sooner rather than later. The initial soft launch on Reddit was to see if anyone else was interested in something like this before I put too much time into the public-facing stuff, and it seems like there is indeed some interest, so I'll be working on some of those things over the next little while.

**Comment by gregdotca** [comment]
I've gone ahead and published an official multi-architecture HomelabAPI docker image, and I've updated the git repo to use this new image, so you should be good to go now! I just tested it on a Pi and it worked perfectly.
