### ISSUE TITLE
Long term notification support

### ISSUE THREAD

**Issue by pewter77** [homelabapi/homelabapi#3]
This might go against what you want, but long term it might be useful to implement the apprise notifications for outputs.

Apprise already has support for a ton of notification services instead of supporting them all manually could make it easier and it's written in python as well!

I absolutely love this project though, had thought about doing something similar before as a sort of gui that inputs any webhook and then allows rules based on url parameters, headers, payload, etc. to then choose an output.

Link for reference:
https://github.com/caronc/apprise

**Comment by gregdotca** [comment]
Implementing Apprise would be pretty easy, and it's something I've been pondering since day one. Part of the reason I built HomelabAPI is to get more familiar with FastAPI though, so if I just import the apprise package and use it for all the outputs, I'll mostly just be getting experience with the apprise package, not FastAPI.

Adding new outputs is generally a fairly straightforward process though, so even without Apprise new ones can be added pretty quickly.
